In [3]:
import torch
x = torch.tensor([0.0],requires_grad=True)
y = torch.tensor([1.0],requires_grad=True)
def func(x,y):
    return(x**2+y**2).sum()
z = func(x,y)

z.backward()

In [4]:
x.grad

tensor([0.])

In [5]:
y.grad

tensor([2.])

In [6]:
def sigmoid1(x):
    return 1 / (1 + torch.exp(-x))

In [7]:
x = torch.tensor([0.0],requires_grad=True)

In [8]:
y = sigmoid1(x)

In [9]:
y.backward()

In [10]:
x.grad

tensor([0.2500])